- src/index.es6
The current result of `cfn-lint --version` is 0.0.1 this change allows the value to match the version of the package.
> Updating to use the package version for the command version

- src/validator.es6
Wildcards are valid strings, as seen in CloudFront headers:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-forwardedvalues.html#cfn-cloudfront-forwardedvalues-headers
> Allow string check to pass on wildcard

- CHANGELOG.md
Not sure if you like this format better or not, but the [keep a changelog](http://keepachangelog.com/en/1.0.0/) CHANGELOG format is pretty nice and keeps a "standardized" approach to making CHANGELOGs. Hope you like it!
> Convert CHANGELOG to more "standard" format

- README.md
- package.json
- src/api.ts
- src/awsData.ts
- src/test/apiTest.ts
- src/test/validatorTest.ts
- src/validator.ts
- testData/invalid/yaml/invalid_outputs.yaml
- testData/valid/yaml/outputs.yaml
- tsconfig.json
Fixes #78 - adds outputs to errorObject and allows cfn-lint to be included as a module.
I first just went to set `main: validator.js` in package.json, however I think the way the caller needs to manage the state of the validator (addParameterValue(), validate(), resetValidator()) is too much of an implementation detail. Hence I hit this away in `api.ts` to make the public facing api as small as possible.
I had a brief look at autogenerating documentation with TypeDoc but IMO it's more trouble than it's worth, and I'm not aware of any other tools that do a decent enough job for a small public api. (they all seem to be more geared at documenting the internals of a large project).
> Allow inclusion as a module

- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/valid_getatt_custom_resource.yaml
Should fix #77 . No way to know what Attributes a CustomResource will have without actually executing it, so it's something we can probably mock.
> allow GetAtt to work on with arbitrary attributes on CustomResources

- CHANGELOG.md
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/issue-94-list-security-group.yaml
> Fix List<ParameterValue> regex

- CHANGELOG.md
- README.md
- src/api.ts
- src/index.ts
- src/test/indexTest.ts
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/no-guess-parameters.yaml
- testData/valid/yaml/parameters.yaml
Implement strict control over how parameter values are guessed.
By default, parameters guessing is unchanged from current behaviour. The parameter will be guessed by looking at the param Default, AllowedValues, and Type properties in that order.
If the `guessParameters` option is set (to a list of parameter names), only parameters which are in that list will be guessed without reporting an error. Any that are absent and that still need to be guessed will cause a critical error to be raised.
From the CLI side this is controlled by the `guess-parameters`/`no-guess-parameters` flags.
From the API side this is controlled by just setting guessParameters in the options - an empty list can be used to disable guessing everything.
> Parameter guessing

- CHANGELOG.md
- package.json
#119 can be easily solved by forcing the `@types/colors` package to the previous version (1.1.3) and perhaps still accept any future patch-level changes (~1.1.3).
> Fixed build - incompatible "@types/colors" package version.

- CHANGELOG.md
- package.json
- src/util/polyfills.ts
Apparently, the current polyfill did not provide a constructor function and therefore `instanceof` failed; I've also noticed a few dissimilarities with the Buffer API.
> Replaced imperfect "safer-buffer" polyfill.

- CHANGELOG.md
- README.md
- src/index.ts
- src/test/indexTest.ts
Fixed #121 and #122. Catches exceptions thrown in template validation and logs `Unable to parse template!` to `stdout`, if `--verbose` flag provided then logs the exception to `stderr`. In both cases the exit code is `1`.
> Handle validation exceptions.

- CHANGELOG.md
- README.md
- data/aws_parameter_types.json
- src/index.ts
- src/test/indexTest.ts
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/parameters_type_commadelimitedlist.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_availabilityzone_name.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_image_id.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_instance_id.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_securitygroup_groupname.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_securitygroup_id.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_subnet_id.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_volume_id.yaml
- testData/valid/yaml/parameters_type_list_aws_ec2_vpc_id.yaml
- testData/valid/yaml/parameters_type_list_aws_route53_hostedzone_id.yaml
- testData/valid/yaml/parameters_type_list_number.yaml
#140 - Fixed parsing of parameter values that contain commas that have been properly escaped using a backslash.
> Issue #140 - Fixed parsing of parameter values that contain commas that have been properly escaped using a backslash.

- CHANGELOG.md
- src/index.ts
- src/test/indexTest.ts
Fixes #110 by updating "--help" to account for the supported commands and to be shown by default in cases where the required arguments are not provided.
> Issue #110 - Updated usage prompt.

- .circleci/config.yml
- CHANGELOG.md
Updated the *CircleCI* docker image to use *NodeJS Boron* running on *Debian Stretch* and ensured that the global `node_modules` directory is in a pristine state.
> Issue #145 - CircleCI build failling

- CHANGELOG.md
- data/aws_intrinsic_functions.json
- package.json
- src/parser.ts
- src/test/validatorTest.ts
- src/test/yamlSchema.ts
- src/validator.ts
- src/yamlSchema.ts
- testData/valid/yaml/split.yaml
This PR implements and tests Fn::Split.
I couldn't do this to begin with as cloudformation-js-yaml-schema does not have a working version available. The current dependency 0.3.1 does not recognize !Split, and the latest version 0.3.4 does not recognize !ImportValue when its argument is a string.
Looking through the source of cloudformation-js-yaml-schema, I believe it will cause yaml parse errors on other inputs as well which might be the source of other bugs. It assumes that arguments to !Tags are a certain type (string, array, obj), and throws a parse error if the type doesn't match. We should be (and generally are) doing that check ourself so we can give better feedback to the user - we should be saying "You can't pass a string to Fn::Join", not "Yaml parse error".
However, we can do …
> Implement Fn::Split, remove cloudformation-js-yaml-schema

- CHANGELOG.md
- README.md
> Cleanup README for v1.7.0 changes

- README.md
- package.json
- src/index.ts
- src/resourcesSpec.ts
- src/test/indexTest.ts
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/smoke.yaml
- testData/valid/yaml/valid_custom_resource_attributes.yaml
Added support for user-defined custom resource attribute values.
> Issue #95 - support for user-defined resource attribute values.

- CHANGELOG.md
- src/test/parserTest.ts
- src/yamlSchema.ts
- testData/valid/yaml/issue_164_getatt_shorthand_parsing.yaml
> Issue #164

- CHANGELOG.md
- README.md
> WIP: Add initial release instructions

- CHANGELOG.md
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/issue_106_conditional_if.yaml
Add support for recursive resolving, which allows for Fn::If parameters to be resolved for whole blocks which depend on a Condition, see #106
> Add support for recursive resolving

- CHANGELOG.md
- src/test/validatorTest.ts
- src/validator.ts
- testData/valid/yaml/valid_nested_intrinsic_subs.yaml
@ronkorving This fixes #195. I'm not too happy about the testability of this logic, and I feel it will be difficult to break out due to the intrinsicResolve dependencies... Any ideas @RazzM13, @akdor1154? 
Anyway, this should fix the issue for now. Will merge into master (if all happy) and release into v1.9.0, when it's unblocked.
> Fn::Sub fixed nested Intrinsic functions and Literal Values

- CHANGELOG.md
- data/aws_resources_specification.json
- src/test/validatorTest.ts
- testData/valid/yaml/issue-214-sqs-queues-now-accept-tags.yaml
Added:
* Fix in AWS definitions
* Issue Test / Fixture
> Issue #214 add tests for SQS Queues Tags

- CHANGELOG.md
- package.json
Update dependency `js-yaml` to fix medium security issue. Snyk report [here](https://snyk.io/vuln/SNYK-JS-JSYAML-173999)
> Updating package dependencies to fix DoS vulnerability
